### ISSUE TITLE
Blocker Plugin für andere Länder erweitern.

### ISSUE THREAD

**Issue by arthurlorenz** [dieparteidiepartei/afd-blocker-plugin#16]
Wir sollten das Plugin auch für andere Länder erweitern, schließlich geht es um die (wieder positive) Besetzung Europas und nicht nur Deutschlands. Habe bereits begonnen das Plugin auf Österreich umzumünzen, um endlich FPÖ-frei Nachrichten lesen zu können.

**Comment by dieparteidiepartei** [comment]
Für ein Europa ohne allgemeine Verblödung.

Als Partei Die PARTEI stehen wir für ein Europa, dass sich über Ländergrenzen hinweg gemeinsam und bewusst der allgemeinen Verblödung entzieht. Den geheimen Code zu unserem AfD-Blocker stellen wir daher als Muster gerne allen zur Verfügung, die in ihrem Land mit ähnlichem Quatsch zu kämpfen haben. Aus rechtlichen Gründen stellt in Eurem Code oder in der Öffentlichkeit aber bitte keine Verbindung zum exklusiv von der Partei „Die PARTEI“ entwickelten „AfD-Blocker“ her. Vielen Dank.
