### ISSUE TITLE
Wie können wir helfen.

### ISSUE THREAD

**Issue by Nitrama** [dieparteidiepartei/afd-blocker-plugin#2]
Hallo,

Ich würde gerne Helfen.

Ich habe schon erfahrung im Addon Programmieren.

Gibt es irgendetwas zu tuhen?

**Comment by dieparteidiepartei** [comment]
Hallo,

gerne weitere Webseiten hinzufügen (focus.de, morgenpost.de, etc.) oder Tickets bearbeiten (dynamisch nachladender Content, etc.)

Viele Grüße
