### ISSUE TITLE
Support für Opera

### ISSUE THREAD

**Issue by larsauswsw** [dieparteidiepartei/afd-blocker-plugin#22]
Blocker bitte auch ifür Opera bereitstellen.

Opera basiert im Großen auf Chrome. Sollte daher nicht all zu großer Aufwand sein,

https://addons.opera.com/de/

**Comment by Biospheere** [comment]
Chrome Extensions funktionieren bereits seit Opera 55 in Opera. Benötigt keine Veränderung des Addon Codes 
https://addons.opera.com/en/extensions/details/install-chrome-extensions/?page=3

**Comment by larsauswsw** [comment]
Sorry, die Entwicklung ist irgendwie an mir vorbeigegangen.
Dann schließe ich das Ticket.
