### ISSUE TITLE
Erweiterung des Suchpatterns

### ISSUE THREAD

**Issue by SebTM** [dieparteidiepartei/afd-blocker-plugin#25]
Aktuell sucht die xPathExpression nur nach "AfD" in genau dieser Schreibweise was u.a. dazu führt, das die Seite der AfD (afd.de) in Suchergebnissen nicht blockiert wird (afd.de != AfD | title = "<title>Home - Alternative für Deutschland</title>")

Ich würde daher vorschlagen, die xPathExpression z.B. auf folgende anzupassen:
```
.//*[contains(text(),'AfD') or contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'),'alternative für deutschland') or contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'),'alternative fuer deutschland')]
```

<img width="1334" alt="Screenshot 2019-05-14 at 15 07 08" src="https://user-images.githubusercontent.com/17243347/57700484-624f2900-765a-11e9-8d2d-44fe2c7edd07.png">

---------------------------------------

Es werden folgende Dinge gesucht:
AfD
Alternative für Deutschland (in allen Schreibweisen)
Alternative fuer Deutschland (in allen Schreibweisen)

Vorher:
<img width="1459" alt="Screenshot 2019-05-14 at 15 04 38" src="https://user-images.githubusercontent.com/17243347/57700301-ff5d9200-7659-11e9-9d59-e9f70801f9b6.png">

Nachher:
<img width="1452" alt="Screenshot 2019-05-14 at 15 05 52" src="https://user-images.githubusercontent.com/17243347/57700324-0a182700-765a-11e9-9776-a6d1f9fc2752.png">

---------------------------------------

Die Erweiterung von "AfD" auf "afd" in allen Schreibweisen, habe ich bewusst wieder herausgenommen, da ggf. auch nicht AfD bezogenen Themen gefiltert werden könnten - wie:

<img width="666" alt="Screenshot 2019-05-14 at 15 06 35" src="https://user-images.githubusercontent.com/17243347/57700367-25833200-765a-11e9-9b0b-aece65bcee3f.png">

Dafür bleiben Links wie folgende aber ebenfalls frei, außer es würde über eine zusätzliche Liste per Hand noch geblockt werden:
<img width="661" alt="Screenshot 2019-05-14 at 15 06 45" src="https://user-images.githubusercontent.com/17243347/57700466-52cfe000-765a-11e9-98bc-9a4a8cc6111f.png">

---------------------------------------

Nachtrag: Die xPathExpression ist teils des Blocker-Cores und betrifft alle Seiten, d.h. die hier abgebildeten Screenshots von qwant.com sind nur exemplarisch.

**Comment by dieparteidiepartei** [comment]
Fixed in #26
