### ISSUE TITLE
Idea: Block certain twitter accounts?

### ISSUE THREAD

**Issue by tiehm** [dieparteidiepartei/afd-blocker-plugin#30]
Another feature could be that tweets from the AfD or people who are followed by the AfD are deleted from your screen. This way you do not have to see those tweets and manually block those people.

**Comment by Biospheere** [comment]
Blocking tweets by people followed by Afd accounts doesn't seem to be a good idea as they often follow serious accounts from news sites and talk shows. Blocking Afd accounts should be enough in my opinion.

**Comment by dieparteidiepartei** [comment]
We are currently blocking tweets with AfD content. To block certain people as well could be a nice improvement. Feel free to contribute ;)
