### ISSUE TITLE
Dynamically added content is not blocked

### ISSUE THREAD

**Issue by mohe2015** [dieparteidiepartei/afd-blocker-plugin#4]
Example page: https://www.sueddeutsche.de/news?search (after https://github.com/dieparteidiepartei/afd-blocker-plugin/pull/3 would be merged)

**Comment by mohe2015** [comment]
This is done by #3

**Comment by RaisingAgent** [comment]
This issue is generally because content scripts are only run once afaik. Maybe we can subscribe to some dom ready event of the site(s)

**Comment by mohe2015** [comment]
> This issue is generally because content scripts are only run once afaik. Maybe we can subscribe to some dom ready event of the site(s)
@RaisingAgent https://github.com/dieparteidiepartei/afd-blocker-plugin/pull/3/commits/85179414bc8c0581d5f3c6d215b318b0a4ed151f I used a mutation observer.

**Comment by dieparteidiepartei** [comment]
Hey,
could you deactivate the observer while running `addBlocker`?

**Comment by RaisingAgent** [comment]
@mohe2015 slighty off topic, but i'm curious. Does `var self = this;` keep the this of the outer scope, whilst this would refer to the current scope in `watchPageForMutations()`.

**Comment by mohe2015** [comment]
@RaisingAgent I'm not a JavaScript expert but I think otherwise `this` refers to the scope of the MutationObserver.
