### ISSUE TITLE
Es braucht noch viel mehr Seiten und vielleicht generische Blocker

### ISSUE THREAD

**Issue by RaisingAgent** [dieparteidiepartei/afd-blocker-plugin#6]
Zumindest alle Springer Zeitungen hätte man bei release drin haben können. :)
Generische Blocker sollten möglich sein. Man kann mit JavaScript ja ganz wunderbar durch den DOM navigieren. Und intelligente Tests, in welchen div, p oder article der zu blockende Artikel ist, sollten auch möglich sein. Ich hab da schon einige Ideen, ich fang mal an zu basteln.
👍

**Comment by pnhofmann** [comment]
> Zumindest alle Springer Zeitungen hätte man bei release drin haben können. :)

Ich dachte dafür hat man schon den ASB installiert? Also den [Axel Springer Blocker](https://chrome.google.com/webstore/detail/axel-springer-blocker-asb/cbnipbdpgcncaghphljjicfgmkonflee/)?

**Comment by dieparteidiepartei** [comment]
Viele Vorschläge haben wir ja schon integriert  - wir freuen uns auf mehr :)
