### ISSUE TITLE
Facebook posts von AfD Seiten und Personen

### ISSUE THREAD

**Issue by RaisingAgent** [dieparteidiepartei/afd-blocker-plugin#7]
Facebook posts von AfD Seiten und Personen sollten auch geblockt werden.

**Comment by McCouman** [comment]
In Arbeit ;)

**Comment by dieparteidiepartei** [comment]
Behoben :)

**Comment by florian-str** [comment]
Es scheint immer noch nicht zu funktionieren
<img width="1409" alt="Bildschirmfoto 2019-05-27 um 20 45 42" src="https://user-images.githubusercontent.com/45917010/58435421-c5ac7280-80c0-11e9-9d09-65b7f533c03c.png">
